// Non-regression cases for the valuation engine (estimation.ts).
// Written before the Next.js port (L1-01): the frozen results in
// __snapshots__ must stay identical after the engine is moved.
// Addresses and figures are realistic inputs from the launch zone (91)
// and from other markets, covering every property type and engine branch.
import { initialForm, type LeenkeyForm, type Lot } from "@/leenkey/estimator/types";

export interface EstimationCase {
  name: string;
  form: LeenkeyForm;
  dvfPrixM2?: number | null;
}

const f = (patch: Partial<LeenkeyForm>): LeenkeyForm => ({ ...initialForm, ...patch });

const lot = (patch: Partial<Lot>): Lot => ({
  id: "lot",
  typologie: "T2",
  surface: 40,
  loyer_hc: 750,
  charges: 50,
  bail_debut: "2022-09-01",
  bail_duree_restante: "2 ans",
  dpe: "D",
  statut: "occupe",
  ...patch,
});

const epinay = { code_postal: "91360", ville: "Épinay-sur-Orge", departement: "91" };
const savigny = { code_postal: "91600", ville: "Savigny-sur-Orge", departement: "91" };

export const cases: EstimationCase[] = [
  {
    name: "appartement T3 Savigny, bon état, DPE D, sans DVF",
    form: f({
      type: "appartement",
      ...savigny,
      adresse: "12 avenue Carnot",
      surface_habitable: 64,
      pieces: 3,
      chambres: 2,
      etage: 2,
      nb_etages_batiment: 4,
      etat: "bon",
      dpe: "D",
      exterieur: ["balcon"],
      exterieur_details: { balcon: 6 },
    }),
  },
  {
    name: "appartement T3 Savigny, même bien avec DVF 3 900 €/m²",
    form: f({
      type: "appartement",
      ...savigny,
      adresse: "12 avenue Carnot",
      surface_habitable: 64,
      pieces: 3,
      chambres: 2,
      etage: 2,
      nb_etages_batiment: 4,
      etat: "bon",
      dpe: "D",
      exterieur: ["balcon"],
      exterieur_details: { balcon: 6 },
    }),
    dvfPrixM2: 3900,
  },
  {
    name: "appartement studio Paris 11e, dernier étage sans ascenseur, DPE G",
    form: f({
      type: "appartement",
      code_postal: "75011",
      ville: "Paris",
      departement: "75",
      surface_carrez: 19,
      pieces: 1,
      etage: 6,
      dernier_etage: true,
      nb_etages_batiment: 6,
      etat: "moyen",
      dpe: "G",
      dpe_date: "2023-03-01",
    }),
    dvfPrixM2: 10200,
  },
  {
    name: "appartement T4 Lyon 6e, excellent état, prestations haut de gamme",
    form: f({
      type: "appartement",
      code_postal: "69006",
      ville: "Lyon",
      departement: "69",
      surface_habitable: 98,
      pieces: 4,
      chambres: 3,
      etage: 3,
      nb_etages_batiment: 5,
      etat: "excellent",
      dpe: "C",
      prestations: ["parquet", "double_vitrage", "lumineux", "sdb_renovee", "quartier_recherche"],
      exterieur: ["cave"],
    }),
    dvfPrixM2: 6100,
  },
  {
    name: "appartement T2 Morsang-sur-Orge à rénover, DPE F, rez-de-chaussée",
    form: f({
      type: "appartement",
      code_postal: "91390",
      ville: "Morsang-sur-Orge",
      departement: "91",
      surface_habitable: 44,
      pieces: 2,
      chambres: 1,
      etage: 0,
      nb_etages_batiment: 3,
      etat: "a_renover",
      dpe: "F",
      charges_copro: 180,
    }),
  },
  {
    name: "maison 5 pièces Épinay-sur-Orge, terrain 520 m², DPE E",
    form: f({
      type: "maison",
      ...epinay,
      adresse: "8 rue de la Fontaine",
      surface_habitable: 112,
      surface_terrain: 520,
      pieces: 5,
      chambres: 4,
      niveaux: 2,
      etat: "bon",
      dpe: "E",
      exterieur: ["jardin", "terrasse"],
      exterieur_details: { jardin: 380, terrasse: 25 },
      annee_construction: "1975",
    }),
  },
  {
    name: "maison Épinay-sur-Orge, même bien avec DVF 3 600 €/m²",
    form: f({
      type: "maison",
      ...epinay,
      adresse: "8 rue de la Fontaine",
      surface_habitable: 112,
      surface_terrain: 520,
      pieces: 5,
      chambres: 4,
      niveaux: 2,
      etat: "bon",
      dpe: "E",
      exterieur: ["jardin", "terrasse"],
      exterieur_details: { jardin: 380, terrasse: 25 },
      annee_construction: "1975",
    }),
    dvfPrixM2: 3600,
  },
  {
    name: "maison Sainte-Geneviève-des-Bois, grande parcelle 2 400 m², piscine",
    form: f({
      type: "maison",
      code_postal: "91700",
      ville: "Sainte-Geneviève-des-Bois",
      departement: "91",
      surface_habitable: 145,
      surface_terrain: 2400,
      pieces: 6,
      chambres: 4,
      etat: "excellent",
      dpe: "C",
      exterieur: ["jardin", "piscine", "dependance"],
      exterieur_details: { piscine: 40, dependance: 35 },
      prestations: ["calme", "lumineux", "cuisine_equipee_electro"],
    }),
    dvfPrixM2: 3400,
  },
  {
    name: "maison de bourg Creuse, petite parcelle, à rénover, DPE inconnu",
    form: f({
      type: "maison",
      code_postal: "23000",
      ville: "Guéret",
      departement: "23",
      surface_habitable: 85,
      surface_terrain: 180,
      pieces: 4,
      chambres: 3,
      etat: "a_renover",
      dpe: "inconnu",
    }),
  },
  {
    name: "maison Haute-Savoie, vue montagne, DPE B",
    form: f({
      type: "maison",
      code_postal: "74400",
      ville: "Chamonix-Mont-Blanc",
      departement: "74",
      surface_habitable: 130,
      surface_terrain: 700,
      pieces: 5,
      chambres: 4,
      etat: "excellent",
      dpe: "B",
      prestations: ["vue_degagee", "calme"],
      exterieur: ["jardin", "terrasse"],
    }),
    dvfPrixM2: 9800,
  },
  {
    name: "terrain à bâtir viabilisé Longjumeau, constructible",
    form: f({
      type: "terrain",
      code_postal: "91160",
      ville: "Longjumeau",
      departement: "91",
      surface_terrain: 600,
      terrain_type: "a_batir",
      constructible: "Oui",
      viabilisation: ["eau", "electricite", "assainissement"],
      facade: 18,
      situation_terrain: "Lotissement",
      topographie: "Plat",
    }),
  },
  {
    name: "terrain constructibilité incertaine en hameau, contraintes",
    form: f({
      type: "terrain",
      code_postal: "91310",
      ville: "Linas",
      departement: "91",
      surface_terrain: 1500,
      terrain_type: "a_batir",
      constructible: "Je ne sais pas",
      situation_terrain: "Hameau",
      contraintes_terrain: ["argiles"],
      vue: ["Campagne"],
    }),
  },
  {
    name: "terrain non constructible agricole",
    form: f({
      type: "terrain",
      code_postal: "91310",
      ville: "Montlhéry",
      departement: "91",
      surface_terrain: 8000,
      terrain_type: "agricole",
      constructible: "Non",
      situation_terrain: "Zone isolée",
    }),
  },
  {
    name: "local commercial boutique rue très commerçante, libre",
    form: f({
      type: "local_commercial",
      code_postal: "91260",
      ville: "Juvisy-sur-Orge",
      departement: "91",
      local_type: "boutique",
      surface_totale: 85,
      surface_vente: 60,
      environnement: "tres_commercante",
      visibilite: "Excellent",
      flux_pieton: "Bon",
      local_occupation: "Libre",
      local_config: ["angle"],
      longueur_vitrine: 7,
    }),
  },
  {
    name: "local commercial restaurant occupé, bail en cours",
    form: f({
      type: "local_commercial",
      code_postal: "91200",
      ville: "Athis-Mons",
      departement: "91",
      local_type: "restaurant",
      surface_totale: 140,
      environnement: "passante",
      visibilite: "Bon",
      flux_pieton: "Moyen",
      local_occupation: "Occupé — bail en cours",
      loyer_annuel: 24000,
      charges_annuelles: 3000,
      taxe_fonciere: 2200,
      bail_duree_restante: "6 ans",
      local_equipements: ["extraction", "pmr"],
    }),
    dvfPrixM2: 2600,
  },
  {
    name: "local commercial bureau en rue secondaire, sans DVF",
    form: f({
      type: "local_commercial",
      code_postal: "69003",
      ville: "Lyon",
      departement: "69",
      local_type: "bureau",
      surface_totale: 120,
      environnement: "secondaire",
      visibilite: "Faible",
      flux_pieton: "Faible",
      local_occupation: "Libre",
    }),
  },
  {
    name: "immeuble de rapport 4 lots occupés Savigny",
    form: f({
      type: "immeuble",
      ...savigny,
      immeuble_type: "rapport",
      immeuble_niveaux: 3,
      surface_totale_immeuble: 240,
      surface_habitable_immeuble: 210,
      lots: [
        lot({ id: "a", typologie: "T2", surface: 45, loyer_hc: 780 }),
        lot({ id: "b", typologie: "T2", surface: 48, loyer_hc: 800 }),
        lot({ id: "c", typologie: "T3", surface: 62, loyer_hc: 980, dpe: "E" }),
        lot({ id: "d", typologie: "Studio", surface: 22, loyer_hc: null, statut: "libre" }),
      ],
      charge_taxe_fonciere: 3800,
      charge_assurance: 1200,
      charge_entretien: 2000,
      etat_technique: { toiture: "Bon", facade: "Moyen", electricite: "À refaire" },
    }),
  },
  {
    name: "immeuble mixte commerce + logements avec DVF",
    form: f({
      type: "immeuble",
      code_postal: "91100",
      ville: "Corbeil-Essonnes",
      departement: "91",
      immeuble_type: "mixte",
      immeuble_niveaux: 4,
      surface_totale_immeuble: 320,
      surface_commerciale: 90,
      lots: [
        lot({
          id: "a",
          typologie: "Local commercial",
          surface: 90,
          loyer_hc: 1400,
          bail_duree_restante: "5 ans",
        }),
        lot({ id: "b", typologie: "T3", surface: 65, loyer_hc: 900 }),
        lot({ id: "c", typologie: "T3", surface: 65, loyer_hc: 920 }),
        lot({ id: "d", typologie: "T2", surface: 45, loyer_hc: 700 }),
        lot({ id: "e", typologie: "Parking", surface: 12, loyer_hc: 60, dpe: null }),
      ],
      charge_taxe_fonciere: 5200,
      charge_assurance: 1800,
    }),
    dvfPrixM2: 2400,
  },
  {
    name: "immeuble sans lots saisis (cas dégradé)",
    form: f({
      type: "immeuble",
      code_postal: "13001",
      ville: "Marseille",
      departement: "13",
      immeuble_type: "rapport",
      surface_totale_immeuble: 180,
    }),
  },
  {
    name: "atypique loft d'architecte Montreuil",
    form: f({
      type: "atypique",
      code_postal: "93100",
      ville: "Montreuil",
      departement: "93",
      atypique_type: "loft",
      surface_habitable: 160,
      etat: "excellent",
      dpe: "C",
      cadre: "Centre-ville",
      calme: "Bon",
      caracteres_exceptionnels: ["volumes", "verriere"],
    }),
    dvfPrixM2: 6300,
  },
  {
    name: "atypique château à restaurer en pleine campagne",
    form: f({
      type: "atypique",
      code_postal: "24200",
      ville: "Sarlat-la-Canéda",
      departement: "24",
      atypique_type: "chateau",
      surface_habitable: 650,
      surface_terrain: 40000,
      nb_batiments: 3,
      surface_dependances: 300,
      etat: "a_renover",
      dpe: "G",
      cadre: "Pleine campagne",
      calme: "Excellent",
      attractivite_touristique: "Excellent",
      classement: ["monument_historique"],
      travaux_budget: 600000,
      potentiel_atypique: ["evenementiel", "gites"],
    }),
  },
  {
    name: "atypique moulin avec revenus de gîte",
    form: f({
      type: "atypique",
      code_postal: "91490",
      ville: "Milly-la-Forêt",
      departement: "91",
      atypique_type: "moulin",
      surface_habitable: 210,
      surface_terrain: 5000,
      etat: "bon",
      dpe: "E",
      cadre: "Village",
      calme: "Bon",
      revenus_existants: 18000,
      cout_entretien_annuel: 6000,
      potentiel_atypique: ["chambres_hotes"],
    }),
    dvfPrixM2: 3100,
  },
  {
    name: "type non renseigné (défaut maison, surface absente)",
    form: f({ type: null, code_postal: "91360", ville: "Épinay-sur-Orge", departement: "91" }),
  },
  {
    name: "appartement minimal (seuls les champs essentiels saisis)",
    form: f({
      type: "appartement",
      code_postal: "91600",
      ville: "Savigny-sur-Orge",
      departement: "91",
      surface_habitable: 58,
      pieces: 3,
      etat: "moyen",
      dpe: "E",
    }),
  },
];
